export function listDocuments() {
  return [
    {
      id: 'doc_auto_insurance',
      title: 'Auto insurance cards',
      category: 'Insurance Cards',
      description: 'Placeholder for Mazda and family vehicle insurance cards.',
      updated: 'Needs Drive auth',
      visibility: 'parents',
      source: 'placeholder',
      icon: '🚗',
    },
    {
      id: 'doc_health_cards',
      title: 'Health insurance cards',
      category: 'Insurance Cards',
      description: 'Quick access spot for medical, dental, and pharmacy cards.',
      updated: 'Needs Drive auth',
      visibility: 'parents',
      source: 'placeholder',
      icon: '🏥',
    },
    {
      id: 'doc_school_forms',
      title: 'School forms',
      category: 'Kids & School',
      description: 'Permission slips, sports forms, and school documents.',
      updated: 'Placeholder',
      visibility: 'family',
      source: 'placeholder',
      icon: '🎒',
    },
    {
      id: 'doc_home_manuals',
      title: 'Home manuals & warranties',
      category: 'Home',
      description: 'Appliance manuals, warranties, and household reference PDFs.',
      updated: 'Placeholder',
      visibility: 'family',
      source: 'placeholder',
      icon: '🏡',
    },
    {
      id: 'doc_emergency',
      title: 'Emergency contacts',
      category: 'Important',
      description: 'Doctors, vets, school, neighbors, and utility emergency numbers.',
      updated: 'Placeholder',
      visibility: 'family',
      source: 'placeholder',
      icon: '⭐',
    },
  ];
}
